### ISSUE TITLE
Minecraft doesn't add Fraiya dimension to the level data after the world has generated

### ISSUE THREAD

**Issue by panaretos** [hYdos/Lint#62] opened 2021-03-05 00:48 UTC

**Comment by valoeghese** [comment] 2021-03-06 05:39
What other mods do you have installed?

**Comment by valoeghese** [comment] 2021-03-06 05:40
And are you sure it's not just lag? Sometimes it can take a few seconds to teleport

**Comment by panaretos** [comment] 2021-03-06 12:09
we have about 65 mods.   the server has been running pretty lag free since we started it a couple months ago.  
it works in single player,  but not on MP server

**Comment by valoeghese** [comment] 2021-03-09 19:42
Does the server work in multiplayer when only the mod is installed?

I'll test it when I have time and see what the issue is

**Comment by valoeghese** [comment] 2021-03-19 21:25
I'm testing this now

**Comment by valoeghese** [comment] 2021-03-19 21:31
It works on my end @panaretos

**Comment by hYdos** [comment] 2021-03-19 21:33
its a bug with dfu. will be fixed soon tm

**Comment by valoeghese** [comment] 2021-03-19 22:08
I tested a second time and it works on my end again. It might be a DFU bug, in which case regenerating the dimension might be the best course idk. Or wait for us to figure out how to use dfu's api.

**Comment by hYdos** [comment] 2021-03-19 22:31
irr

**Comment by valoeghese** [comment] 2021-03-20 00:41
If this is still an issue don't close it

**Comment by hYdos** [comment] 2021-03-20 00:43
:tiny

**Comment by TelepathicGrunt** [comment] 2021-04-19 02:49
suggestion, make the dimension be a worldgen json file instead. And then use this mixin to feed the real world seed to the biome source/chunk generator.

https://github.com/TelepathicGrunt/WorldBlender-Fabric/blob/35e2237f7657487b8c38ae649f79d5e7a513397e/src/main/java/com/telepathicgrunt/worldblender/mixin/dimensions/GeneratorOptionsMixin.java#L24

Worldgen json files makes it easier to create dimensions as minecraft will just work(tm) and make it for you

**Comment by valoeghese** [comment] 2021-04-22 06:06
Hydos, we must use ARRp to anti-json this json

**Comment by valoeghese** [comment] 2021-08-28 02:44
plsfix

**Comment by valoeghese** [comment] 2021-10-03 21:32
working on this now

**Comment by valoeghese** [comment] 2021-10-04 05:03
probably fixed

**Comment by valoeghese** [comment] 2021-10-04 05:03
thanks tele

**Closed as completed by valoeghese** 2021-10-04 05:03 UTC
Labels: bug, help wanted
